# Title: BioCypher graph schema configuration file
# # ---
# # "Named Things"
# # ---

# gene:
#   represented_as: node
#   preferred_id: ensemble
#   input_label: gene
#   properties:
#     chr: str
#     start: int
#     end: int
#     name: str
#     gene_type: str
#     synonyms: str[]
#     source: str
#     version: str
#     source_url: str

# protein:
#   represented_as: node
#   preferred_id: uniprot
#   input_label: protein
#   properties:
#     accessions: int
#     organism_id: int
#     name: str
#     synonyms: str[]
#     source: str
#     version: str
#     source_url: str

# transcript:
#   represented_as: node
#   input_label: transcript
#   properties:
#     chr: str
#     start: int
#     end: int
#     gene_name: str
#     transcript_name: str
#     transcript_id: str
#     transcript_type: str
#     source: str
#     version: str
#     source_url: str
#   is_a: nucleic acid entity
#   description: >-
#     An RNA synthesized on a DNA or RNA template by an RNA polymerase.
#   exact_mappings:
#     - SO:0000673
#     - SIO:010450
#     - WIKIDATA:Q7243183
#     - dcid:RNATranscript
#   in_subset:
#     - model_organism_database
  
# regulatory region:
#   represented_as: node
#   input_label: regulatory_region
#   properties:
#     chr: str
#     start: int
#     end: int
#     biological_context: str
#     biochemical_activity: str
# #    biochemical_activity_description: str
#     source: str
#     source_url: str
#   aliases: ['regulatory element', 'accessible dna element']
#   description: >-
#     A region (or regions) of the genome that contains known or putative regulatory elements
#     that act in cis- or trans- to affect the transcription of gene
#   is_a: biological entity
#   mixins:
#     - genomic entity
#     - chemical entity or gene or gene product
#     - physical essence
#     - ontology class
#   exact_mappings:
#     - SO:0005836
#     - SIO:001225
#     - WIKIDATA:Q3238407

# ontology term:
#   is_a: ontology class
#   represented_as: node
#   input_label: ontology term
#   properties:
# #    uri: str
#     term_name: str
#     description: str
#     synonyms: obj
#     subontology: str
#     subset: str
#     source: str
#     source_url: str

# pathway:
#   is_a: biological process
#   exact_mappings:
#     - PW:0000001
#     - WIKIDATA:Q4915012
#   narrow_mappings:
#     - SIO:010526
#     - GO:0007165
#   represented_as: node
#   input_label: pathway
#   properties:
#     id_version: str
#     name: str
#     is_in_disease: boolean
#     name_aliases: array
#     species: str
#     disease_ontology_terms: array
#     go_biological_process: str
#     is_top_level_pathway: boolean
#     source: str
#     source_url: str

# tad:
#   is_a: entity
#   represented_as: node
#   input_label: tad
#   properties:
#     chr: str
#     start: int
#     end: int
#     genes: str[]
#     source: str
#     source_url: str

# motif:
#   represented_as: node
#   is_a: ontology class
#   input_label: motif
#   db_collection_name: motifs
#   db_collection_per_chromosome: false
#   db_indexes:
#     text:
#       type: inverted
#       fields: tf_name
#   accessible_via:
#     name: motifs
#     description: 'TF binding motifs.'
#     fuzzy_text_search: tf_name
#     return: _id, tf_name, source, source_url, pwm, length
#   properties:
#     tf_name: str
#     source: str
#     source_url: str
#     pwm_A: float[]
#     pwm_C: float[]
#     pwm_G: float[]
#     pwm_T: float[]
#     length: str

# # ---
# # Associations
# # ---

# transcribed to:
#   represented_as: edge
#   is_a: related to at instance level
#   domain: gene
#   range: transcript
#   input_label: transcribed_to
#   source: gene
#   target: transcript
#   properties:
#     source: str
#     version: str
#     source_url: str
#   description: >-
#     inverse of transcribed from
#   exact_mappings:
#     - RO:0002511
#     - SIO:010080

# transcribed from:
#   is_a: related to at instance level
#   represented_as: edge
#   domain: transcript
#   range: gene
#   input_label: transcribed_from
#   source: transcript
#   target: gene
#   properties:
#     source: str
#     version: str
#     source_url: str
#   description: >-
#     x is transcribed from y if and only if x is synthesized from template y
#   exact_mappings:
#     - RO:0002510
#     - SIO:010081

# translates to:
#   is_a: related to at instance level
#   represented_as: edge
#   input_label: translates_to
#   source: transcript
#   target: protein
#   properties:
#     source: str
#     source_url: str
#   inverse: translation of
#   description: >-
#     x (amino acid chain/polypeptide) is the ribosomal translation of y (transcript) if and only if a ribosome
#     reads y (transcript) through a series of triplet codon-amino acid adaptor activities (GO:0030533)
#     and produces x (amino acid chain/polypeptide)
#   close_mappings:
#     - RO:0002513
#     - SIO:010082

# translation of:
#   is_a: related to at instance level
#   represented_as: edge
#   input_label: translation_of
#   source: protein
#   target: transcript
#   properties:
#     source: str
#     source_url: str
#   description: >-
#     inverse of translates to
#   inverse: translates to
#   close_mappings:
#     - RO:0002512
#     - SIO:010083

# gene to pathway association:
#   description: >-
#     An interaction between a gene or gene product and a biological process or pathway.
#   is_a: association
#   mixins:
#     - gene to entity association mixin
#   represented_as: edge
#   input_label: genes_pathways
#   source: gene
#   target: pathway

# parent pathway of:
#     is_a: related to at concept level
#     description: >-
#       holds between two pathways where the domain class is a parent pathway of the range class
#     represented_as: edge
#     input_label: parent_pathway_of
#     source: pathway
#     target: pathway

# child pathway of:
#     is_a: related to at concept level
#     description: >-
#       holds between two pathways where the domain class is a child pathway of the range class
#     represented_as: edge
#     input_label: child_pathway_of
#     source: pathway
#     target: pathway

# ontology relationship:
#   is_a: related to at instance level
#   represented_as: edge
#   input_label: ontology_relationship
#   source: ontology term
#   target: ontology term
#   properties:
#     rel_type: str
#     source: str

# go gene product:
#   is_a: related to at instance level
#   represented_as: edge
#   input_label: go_gene_product
#   source: ontology term
#   target: protein
#   properties:
#     qualifier: obj
#     db_reference: obj
#     evidence: str
#     source: str
#     source_url: str

# gene to gene coexpression association:
#   description: >-
#     Indicates that two genes are co-expressed,
#     generally under the same conditions.
#   is_a: gene to gene association
#   defining_slots:
#     - subject
#     - predicate
#     - object
#   mixins:
#     - gene expression mixin
#   slot_usage:
#     predicate:
#       subproperty_of: coexpressed with
#       symmetric: true
#   represented_as: edge
#   input_label: coexpressed_with
#   source: gene
#   target: gene
#   properties:
#     score: int
#     source: str
#     source_url: str
#     version: str

# regulatory element to gene expression association:
#   description: >-
#     An association between a regulatory element and the expression of a gene
#   is_a: association
#   defining_slots:
#     - subject
#     - predicate
#     - object
#   slot_usage:
#     object:
#       range: gene
#     predicate:
#       subproperty_of: genetic association
#   represented_as: edge
#   input_label: regulates_gene
#   label_as_edge: ELEMENT_GENE
#   source: regulatory region
#   target: gene
#   properties:
#     score: int
#     source: str
#     source_url:  str
#     biological_context: str


# transcription factor to gene association:
#   description: >-
#     An regulatory association between a transcription factor and its target gene
#   is_a: gene to gene association
#   represented_as: edge
#   input_label: regulates
#   source: gene
#   target: gene
#   properties:
#     evidence: str[]
#     detection_method: str
#     databases: str[]
#     evidence_type: str
#     source: str,
#     source_url: str

# post translational interaction:
#   is_a: pairwise molecular interaction
#   represented_as: edge
#   input_label: interacts_with
#   source: protein
#   target: protein
#   properties:
#     score: float,
#     source: str,
#     source_url: str,
#     version: str

# gtex variant to gene expression association:
#   aliases: [ 'eQTL', 'e-QTL']
#   description: >-
#     An association between a variant and expression of a gene (i.e. e-QTL)
#   is_a: variant to gene association
#   defining_slots:
#     - subject
#     - predicate
#     - object
#   mixins:
#     - gene expression mixin
#   slot_usage:
#     predicate:
#       subproperty_of: affects
#   represented_as: edge
#   input_label: eqtl
#   source: sequence variant
#   target: gene
#   accessible_via:
#     name: e-qtls
#     description: 'Retrieve e-qtls data along with correspondent variants and genes'
#     filter_by: beta, slope, source, label, p_value
#     filter_by_range: beta, p_value, slope
#     return: p_value, slope, beta, label, chr, source, source_url, biological_context
#   properties:
#     chr: str
#     rsId: str
#     slope: float
#     maf: float
#     p_value: float
#     q_value: float
#     biological_context: str
#     source: str
#     source_url: str

# topld in linkage disequilibrium with:
#   is_a: related to at instance level
#   description: holds between two sequence variants, the presence of which are correlated
#     in a population
#   symmetric: true
#   annotations:
#     canonical_predicate: true
#   exact_mappings:
#     - NCIT:C16798
#   represented_as: edge
#   input_label: in_ld_with
#   db_collection_per_chromosome: false
#   source: sequence variant
#   target: sequence variant
#   accessible_via:
#     name: variants_variants
#     description: 'Retrieve variant correlation data. Example: r2 = gt:0.8, d_prime = lte:0.5, ancestry = SAS'
#     filter_by: r2, d_prime, ancestry, label
#     filter_by_range: r2, d_prime
#     return: chr, ancestry, d_prime, label, r2, variant_1_base_pair, variant_1_rsid, variant_2_base_pair, variant_2_rsid, source, source_url
#   properties:
#     chr: str
#     ancestry: str
#     r2: float
#     d_prime: float
#     source: str
#     source_url: str